import 'package:get/get.dart';

class TranslateData extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'login_with_mobile': 'Login With Mobile',
          'next': 'Next',
          'login_with_gmail': 'Login with gmail',
          'skip': 'Skip >>  ',
          'send': 'Send',
          'resend': 'ReSend  ',
          'enter_mobile': "Enter mobile",
          'or': "OR",
          'my_cart': "My Cart",
          'training': "Training",
          'meri_dukaan': "Meri Dukaan",
          'home': "Home",
          'rent_sell': "Rent/Sell",
          'banking': "Banking",
          'profile': "Profile",
          "create_shop": "Create Online Dukaan",
          'contact_us': "Contact Us",
          'new_and_video': "News And Video",
          'shipping_And_delivery_policy': "Shipping And Delivery Policy",
          'seller_term_and_condition': "Seller Term And Condition",
          'privacy_policy': "Privacy Policy",
          'cancellation_policy': "Cancellation Policy",
          'terms_conditions': "Terms and Conditions",
          'faqs': "FAQ's",
          'rafferal_code': "Rafferal Code",
          "visit_faceBook": "Visit FaceBook",
          'visit_youTube': "Visit YouTube",
          'log_out': "Log out",
          'share_app': "Share App",
          'about_us': "About Us",
          'support_and_security': "Support and Security",
          'product_category': "Search for Product,Category",
          'browse_categories': "Browse Categories",
          'see_all': "See All >>",
          'All_ATEGORY': "All CATEGORY",
          "recommended_product": "Recommended Products",
          'best_seller_product': "Best Seller Products",
          'all_product': "All Products",
          'sub_category': "Sub Category",
          'upload_you_post': "Upload you post",
          'upload_image': "Upload image",
          'product_name': "Product Name",
          'product_fee': "Product Price",
          'product_old_fee': "product old Fee",
          'type_of_product': "Type Of Product",
          'buy': "Buy",
          'rent': "Rent",
          'sell': "Sell",
          'product_name_validation': "Please enter product name",
          'product_name_price_validation': "Please enter product price",
          'product_car_id_validation': "Please select category",
          'product_sub_id_validation': "Please select sub category",
          'all_sub_cat': "All sub category",
          'browse_sub_categories': "Browse Sub Categories",
          "apply_now": "Apply Now",
          "about_training_text":
              "Over 40,000 Farmers have benefitted after availing Training from F2DF.COM on Innovative Farm Techniques and other best Practices. We offer both ONLINE & OFFLINE Training depending upon the Training Content, Availability of Trainer and other factors. We offer Training in wide variety of Topics concerning Agriculture & Allied Services through a network of Experts, Organic & Progressive Farmers and people from Academia. Come be a part of New India and March towards Prosperity and economic independence with us.",
          "about_training": "About Training",
          "apply_loan": "Apply for Loan",
          "apply_for_Insurance": "Apply for Insurance",
          "apply_loan_about":
              "Agricultural loan can be availed to meet a variety of expenses related to farm activities, such as to purchase new farmland/ cattle or to manage the operating costs and other allied activities and meet other household needs. F2DF.COM has a wide network of Banks and other Financial Institutions to help you with loans as per your requirement. We guarantee you the best terms and faster disbursal of loan amount if applied through us.",
          "apply_insaurance_about":
              "Crop insurance is a means of protecting the agriculturist against financial losses due to uncertainties that may arise from crop failures/losses arising from named or all unforeseen perils beyond their control. providing financial support to farmers suffering crop loss/damage arising out of unforeseen events. We at F2DF.COM are deeply concern about Farmer well being and would want every Farmer family to stay safe and due not suffer financial losses. We will help you with best rates and timely resolution of your claims if you apply through us. We have a wide network of companies working for your benefit.",
          "something_went_wrong!": "Something went wrong!",
          "enter_user_name": "Enter user Name",
          "enter_your_email": "Enter your email",
          "crop_insurance_amount":"Crop Insurance Amount",
          "loan_amount":"Loan Amount",
          "enter_user_mobile": "Enter user mobile",
          "enter_user_address": "Enter user address",
          "enter_user_message": "Enter user inquiry",
          "enter_user_description": "Enter user description",
          "enter_training_date": "Training date",
          "enquiry": "Enquiry",
          "product": "Product",
          "my_company_my_dukaan": "Company name /My dukaan name",
          "shop_tag_line": "My shop tag line",
          "year_of_establish": "Year of establish",
          "nature_of_business": "Nature of business",
          "email": "Email",
          "mobile": "Phone number",
          "address": "Address",
          "whatsapp_number": "WhatsApp number",
          "gst_number": "GST number",
          "shop_link": "Create my shop link and sending URL",
          "facebook_link": "Facebook link",
          "linkedin_link": "Linkedin link",
          "twitter_link": "Twitter link",
          "instagram_link": "Instagram link",
          "youtube_link": "Youtube link",
          "github_link": "Github link",
          "please_enter_company_name": "Please enter company name",
          "please_enter_phone_number": "Please enter phone number",
          "check_url": "Check",
          "please_enter_company_url": "Please enter company url",
          "my_product": "My Product",
          "view_Online_dukaan": "View Online dukaan",
          "more": "More",
          "export": "Export",
          'our_product': "My Products",
          "boost_your_product": "BOOST YOUR PRODUCT",
          "edit": "Edit",
          "seller_availability": "Seller Availability",
          "buyer_requirement": "Buyer Requirement",
          "delete": "Delete",
          "delete_title": "Delete Product",
          "delete_msg": "Would you like to delete this product?",
          "yes": "Yes",
          "no": "NO",
          "shipping":"Shipping",
          "subTotal":"SubTotal",
          "total_amount":"Total Amount",
          "proceed_to_pay":"Proceed to pay",
          "mobile_validation":"Please enter mobile number",
          "name_validation":"Please enter your name",
          "urgent_requirement":"URGENT REQUIREMENT"
        },
        'hi_IN': {
          'login_with_mobile': 'मोबाइल से लॉग इन करें',
          'next': 'अगला',
          'login_with_gmail': 'जीमेल से लॉग इन करें',
          'skip': 'छोड़ें >>  ',
          'send': 'भेजना',
          'resend': 'पुन: भेजें   ',
          'enter_mobile': "मोबाइल दर्ज करें",
          'or': "या",
          'my_cart': "मेरी गाड़ी",
          'training': "प्रशिक्षण",
          'meri_dukaan': "मेरी दुकान",
          'home': "घर",
          'rent_sell': "किराया/बेचना",
          'banking': "बैंकिंग",
          'profile': "प्रोफ़ाइल",
          'contact_us': "संपर्क करें",
          'new_and_video': "समाचार और वीडियो",
          'shipping_And_delivery_policy': "शिपिंग और वितरण नीति",
          'seller_term_and_condition': "विक्रेता नियम और शर्त",
          'privacy_policy': "गोपनीयता नीति",
          'cancellation_policy': "रद्द करने की नीति",
          'terms_conditions': "नियम एवं शर्तें",
          'faqs': "अक्सर पूछे जाने वाले प्रश्न",
          'rafferal_code': "रेफरल कोड",
          "visit_faceBook": "फेसबुक पर जाएँ",
          'visit_youTube': "यूट्यूब पर जाएँ",
          'log_out': "लॉग आउट",
          'share_app': "ऐप शेयर करें",
          'about_us': "हमारे बारे में",
          'support_and_security': "समर्थन और सुरक्षा",
          'product_category': "उत्पाद श्रेणी",
          'browse_categories': "श्रेणियाँ ब्राउज़ करें",
          'see_all': "सभी देखें >>",
          'All_ATEGORY': "सभी श्रेणी",
          "recommended_product": "अनुशंसित उत्पाद",
          'best_seller_product': "सर्वश्रेष्ठ विक्रेता उत्पाद",
          'all_product': "सभी उत्पाद",
          'sub_category': "उप श्रेणी",
          'upload_you_post': "आप पोस्ट अपलोड करें",
          'upload_image': "तस्विर अपलोड करना",
          'product_name': "प्रोडक्ट का नाम",
          'product_fee': "उत्पाद की कीमत",
          'product_old_fee': "उत्पाद पुराना शुल्क",
          'type_of_product': "उत्पाद के प्रकार",
          'buy': "खरीदना",
          'rent': "किराया",
          'sell': "बेचना",
          'product_name_validation': "कृपया उत्पाद का नाम दर्ज करें",
          'product_name_price_validation': "कृपया उत्पाद की कीमत दर्ज करें",
          'product_car_id_validation': "कृपया श्रेणी चुनें",
          'product_sub_id_validation': "कृपया उप श्रेणी चुनें",
          'all_sub_cat': "सभी उप श्रेणी",
          'browse_sub_categories': "उप श्रेणियाँ ब्राउज़ करें",
          "apply_now": "अभी आवेदन करें",
          "about_training_text":
              "नवोन्मेषी कृषि तकनीकों और अन्य सर्वोत्तम प्रथाओं पर F2DF.COM से प्रशिक्षण प्राप्त करने के बाद 40,000 से अधिक किसान लाभान्वित हुए हैं। हम प्रशिक्षण सामग्री, प्रशिक्षक की उपलब्धता और अन्य कारकों के आधार पर ऑनलाइन और ऑफलाइन दोनों माध्यमों से प्रशिक्षण प्रदान करते हैं। हम विशेषज्ञों, जैविक और प्रगतिशील किसानों और अकादमिक लोगों के नेटवर्क के माध्यम से कृषि और संबद्ध सेवाओं से संबंधित विविध विषयों में प्रशिक्षण प्रदान करते हैं। आइए नए भारत का हिस्सा बनें और हमारे साथ समृद्धि और आर्थिक स्वतंत्रता की ओर बढ़ें।",
          "about_training": "प्रशिक्षण के बारे में",
          "apply_loan": "ऋण के लिए आवेदन करें",
          "apply_for_Insurance": "बीमा के लिए आवेदन करें",
          "apply_loan_about":
              "कृषि गतिविधियों से संबंधित विभिन्न प्रकार के खर्चों को पूरा करने के लिए कृषि ऋण का लाभ उठाया जा सकता है, जैसे कि नई कृषि भूमि / मवेशी खरीदना या परिचालन लागत और अन्य संबद्ध गतिविधियों का प्रबंधन करना और अन्य घरेलू जरूरतों को पूरा करना। F2DF.COM के पास आपकी आवश्यकता के अनुसार ऋण देने में आपकी सहायता करने के लिए बैंकों और अन्य वित्तीय संस्थानों का एक विस्तृत नेटवर्क है। यदि हमारे माध्यम से आवेदन किया जाता है तो हम आपको सर्वोत्तम शर्तों और ऋण राशि के तेजी से वितरण की गारंटी देते हैं।",
          "apply_insaurance_about":
              "फसल बीमा कृषकों को अनिश्चितताओं के कारण होने वाले वित्तीय नुकसान से बचाने का एक साधन है, जो फसल की विफलता से उत्पन्न होने वाले नुकसान या उनके नियंत्रण से परे सभी अप्रत्याशित खतरों से उत्पन्न हो सकता है। अप्रत्याशित घटनाओं से होने वाली फसल हानि/क्षति से पीड़ित किसानों को वित्तीय सहायता प्रदान करना इसका मुख्य उद्देश्य है। F2DF.COM पर हम किसान कल्याण के बारे में गहरी चिंता रखते हैं और चाहते हैं कि प्रत्येक किसान परिवार सुरक्षित रहे और उसका वित्तीय नुकसान न हो। यदि आप हमारे माध्यम से आवेदन करते हैं तो हम आपके दावों के समय पर समाधान में आपकी सहायता करेंगे। हमारे पास आपके लाभ के लिए काम करने वाली कंपनियों का एक विस्तृत नेटवर्क है।",
          "something_went_wrong!": "कुछ गलत हो गया!",
          "enter_user_name": "उपयोगकर्ता नाम दर्ज करें",
          "enter_your_email": "अपना ईमेल दर्ज करें",
          'crop_insurance_amount':"फसल बीमा राशि",
          "loan_amount":"उधार की राशि",
          "enter_user_mobile": "उपयोगकर्ता मोबाइल दर्ज करें",
          "enter_user_address": "उपयोगकर्ता पता दर्ज करें",
          "enter_user_message": "उपयोगकर्ता पूछताछ दर्ज करें",
          "enter_user_description": "उपयोगकर्ता विवरण दर्ज करें",
          "enter_training_date": "प्रशिक्षण तिथि",
          "enquiry": "जाँच करना",
          "product": "उत्पाद",
          "create_shop": " ऑनलाइन दुकान बनाएँ",
          "my_company_my_dukaan": "कंपनी का नाम /मेरी दुकान का नाम",
          "shop_tag_line": "मेरी दुकान टैग लाइन",
          "year_of_establish": "स्थापना का वर्ष",
          "nature_of_business": "व्यवसाय की प्रकृति",
          "email": "ईमेल",
          "mobile": "फ़ोन नंबर",
          "address": "पता",
          "whatsapp_number": "व्हाट्सएप नंबर",
          "gst_number": "जीएसटी नंबर",
          "shop_link": "मेरी दुकान का लिंक बनाएं और यूआरएल भेजें",
          "facebook_link": "फेसबुक लिंक",
          "linkedin_link": "लिंक्डइन लिंक",
          "twitter_link": "ट्विटर लिंक",
          "instagram_link": "इंस्टाग्राम लिंक",
          "youtube_link": "इयूट्यूब लिंक",
          "github_link": "जीथब लिंक",
          "please_enter_company_name": "कृपया कंपनी का नाम दर्ज करें",
          "please_enter_phone_number": "कृपया फ़ोन नंबर दर्ज करें",
          "check_url": "जांच",
          "please_enter_company_url": "कृपया कंपनी url दर्ज करें",
          "my_product": "मेरा उत्पाद",
          "view_Online_dukaan": "ऑनलाइन दुकान देखें",
          "more": "अधिक",
          "export": "निर्यात करना",
          'our_product': "हमारे उत्पाद",
          "boost_your_product": "अपने उत्पाद को बढ़ावा दें",
          "edit": "संपादन करना",
          "seller_availability": "विक्रेता उपलब्धता",
          "buyer_requirement": "खरीदार की आवश्यकता",
          "delete": "मिटाना",
          "delete_title": "उत्पाद हटाएं",
          "delete_msg": "क्या आप इस उत्पाद को हटाना चाहेंगे?",
          "yes": "हाँ",
          "no": "नहीं",
          "shipping":"शिपिंग",
          "subTotal":"उप-योग",
          "total_amount":"कुल राशि",
          "proceed_to_pay":"बिल का भुगतान",
          "mobile_validation":"कृपया मोबाइल नंबर दर्ज करें",
          "name_validation":"कृपया अपना नाम दर्ज करें",
          "urgent_requirement":"तुरंत आवश्यकता!"
        },
      };
}
